

### 멤버회원가입
# @no-cookie-jar
POST http://localhost:8080/accounts/signup
Content-Type: application/json


  {
    "id": "admin1",
    "password": "1234",
    "email": "admin1@mail.com",
    "name": "관리자1"
  }
###
POST http://localhost:8080/accounts/signup
Content-Type: application/json


{
  "id": "user1",
  "password": "5678",
  "email": "user1@mail.com",
  "name": "유저1"
}
###
POST http://localhost:8080/accounts/signup
Content-Type: application/json


{
  "id": "user2",
  "password": "9876",
  "email": "user2@mail.com",
  "name": "유저2"
}

###멤버조회
GET http://localhost:8080/accounts/loginId/user1
Content-Type: application/json


### 해당정보 존재하면 로그인
POST http://localhost:8080/accounts/login
Content-Type: application/json

{
  "id": "user1",
  "password": "5678"
}

### 해당 이메일 존재하면 이메일로 로그인
POST http://localhost:8080/accounts/login/email
Content-Type: application/json

{
  "email": "user1@mail.com"
}


### 탈퇴했을시 상태를 탈퇴로 변경
PUT http://localhost:8080/accounts/2/drop
Content-Type: application/json

### 관리자만 휴면 상태로 변경 가능
PUT http://localhost:8080/accounts/1/sleep/3
Content-Type: application/json

