###
POST http://localhost:8080/accounts/signup
Content-Type: application/json


  {
  "id": "user1",
  "password": "1234",
  "email": "user1@mail.com",
  "name": "유저1"
  }
###
POST http://localhost:8080/accounts/signup
Content-Type: application/json


{
  "id": "user2",
  "password": "5678",
  "email": "user2@mail.com",
  "name": "유저2"
}



###
GET http://localhost:8080/accounts/login
Content-Type: application/json

{
  "id": "user1",
  "password": "1234"
}

###
GET http://localhost:8080/account/login/email
Content-Type: application/json

{
  "email": "user1@mail.com"
}

###
GET http://localhost:8080/accounts


###
GET http://localhost:8080/accounts/1

###
DELETE http://localhost:8080/accounts/1